"""empty message

Revision ID: 148c675a24d8
Revises: 687b6e161d04
Create Date: 2024-09-16 08:54:44.350535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148c675a24d8'
down_revision = '687b6e161d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_theme', schema=None) as batch_op:
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
