"""Initial migration.

Revision ID: 55c50194df24
Revises: e060d6adf28d
Create Date: 2024-12-22 19:06:03.203479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c50194df24'
down_revision = 'e060d6adf28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_theme_message', schema=None) as batch_op:
        batch_op.drop_constraint('forum_theme_message_text_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_theme_message', schema=None) as batch_op:
        batch_op.create_unique_constraint('forum_theme_message_text_key', ['text'])

    # ### end Alembic commands ###
