"""empty message

Revision ID: 687b6e161d04
Revises: eac8bead22ba
Create Date: 2024-09-16 08:05:36.056457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687b6e161d04'
down_revision = 'eac8bead22ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_theme',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'theme_id'),
    info={'bind_key': None}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_theme')
    # ### end Alembic commands ###
