"""empty message

Revision ID: 853e8b571d25
Revises: f54e0169ee73
Create Date: 2024-09-15 10:44:58.914445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853e8b571d25'
down_revision = 'f54e0169ee73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_constraint('block_order_in_course_key', type_='unique')

    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.drop_constraint('theme_order_in_block_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.create_unique_constraint('theme_order_in_block_key', ['order_in_block'])

    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.create_unique_constraint('block_order_in_course_key', ['order_in_course'])

    # ### end Alembic commands ###
