"""empty message

Revision ID: cb8bc06438ff
Revises: d5931dbbc412
Create Date: 2024-09-16 21:03:06.666839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8bc06438ff'
down_revision = 'd5931dbbc412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'theme', ['theme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('theme_id')

    # ### end Alembic commands ###
