"""empty message

Revision ID: d5931dbbc412
Revises: 148c675a24d8
Create Date: 2024-09-16 20:39:56.846693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5931dbbc412'
down_revision = '148c675a24d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_text', sa.String(length=1200), nullable=False),
    sa.Column('answer', sa.String(length=1200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coding_task')
    # ### end Alembic commands ###
