"""empty message

Revision ID: d6706ca4240b
Revises: d101fb08a16c
Create Date: 2024-09-15 10:26:19.501639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6706ca4240b'
down_revision = 'd101fb08a16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_in_block', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('block_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['number_in_block'])
        batch_op.drop_constraint('theme_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'block', ['block_id'], ['id'])
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('theme_course_id_fkey', 'course', ['course_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('block_id')
        batch_op.drop_column('number_in_block')

    op.drop_table('block')
    # ### end Alembic commands ###
