"""Initial migration.

Revision ID: e060d6adf28d
Revises: 645bd9c8069b
Create Date: 2024-12-22 18:53:25.120007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e060d6adf28d'
down_revision = '645bd9c8069b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_viewed_forum_theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_viewed_forum_theme_forum_theme_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'forum_theme', ['theme_id'], ['id'])
        batch_op.drop_column('forum_theme_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_viewed_forum_theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forum_theme_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_viewed_forum_theme_forum_theme_id_fkey', 'forum_theme', ['forum_theme_id'], ['id'])
        batch_op.drop_column('theme_id')

    # ### end Alembic commands ###
