"""empty message

Revision ID: f54e0169ee73
Revises: d6706ca4240b
Create Date: 2024-09-15 10:29:02.201704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54e0169ee73'
down_revision = 'd6706ca4240b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_in_course', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['order_in_course'])

    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_in_block', sa.Integer(), nullable=False))
        batch_op.drop_constraint('theme_number_in_block_key', type_='unique')
        batch_op.create_unique_constraint(None, ['order_in_block'])
        batch_op.drop_column('number_in_block')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_in_block', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('theme_number_in_block_key', ['number_in_block'])
        batch_op.drop_column('order_in_block')

    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('order_in_course')

    # ### end Alembic commands ###
