"""empty message

Revision ID: fe9f4c58c2cc
Revises: cb8bc06438ff
Create Date: 2024-09-16 21:49:04.868260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9f4c58c2cc'
down_revision = 'cb8bc06438ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_coding_task',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coding_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coding_task_id'], ['coding_task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'coding_task_id'),
    info={'bind_key': None}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_coding_task')
    # ### end Alembic commands ###
