version: '3'

services:
  web:
    build: ./app
    ports:
      - "5000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./certs/key.pem:/etc/ssl/certs/key.pem
    networks:
      - app-network

  post_service:
    build: ./post_service
networks:
  app-network:
    driver: bridge
